// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-quotes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_quotes_default = defineTool({
  name: "list_quotes",
  title: "Elenca preventivi",
  description: "Elenca i preventivi dell'utente autenticato, dal pi\xF9 recente. Filtri opzionali per cliente e limite.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Numero massimo di risultati (default 20)."),
    client_name: z.string().optional().describe("Filtro parziale case-insensitive sul nome cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, client_name }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    let q = sb(ctx).from("quotes").select("id, quote_number, client_name, date, status, total_amount, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (client_name) q = q.ilike("client_name", `%${client_name}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-quote.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_quote_default = defineTool2({
  name: "get_quote",
  title: "Dettaglio preventivo",
  description: "Restituisce il preventivo completo (sezioni, voci, totali, note) per l'id indicato.",
  inputSchema: { id: z2.string().uuid().describe("UUID del preventivo.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const { data, error } = await sb2(ctx).from("quotes").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Preventivo non trovato" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { quote: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "Elenca clienti",
  description: "Elenca i clienti dell'utente autenticato. Ricerca opzionale su nome/azienda/email.",
  inputSchema: {
    search: z3.string().optional().describe("Ricerca parziale case-insensitive su nome, azienda o email."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    let q = sb3(ctx).from("clients").select("id, name, company, email, phone, vat_number, created_at").order("name").limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,company.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool4({
  name: "list_products",
  title: "Elenca prodotti",
  description: "Elenca i prodotti a listino (DT) dell'utente. Ricerca opzionale su nome/codice/categoria.",
  inputSchema: {
    search: z4.string().optional().describe("Ricerca parziale case-insensitive su nome, codice o categoria."),
    include_archived: z4.boolean().optional().describe("Includere prodotti archiviati (default false)."),
    limit: z4.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    let q = sb4(ctx).from("products").select("id, name, code, category, unit, price_dt, archived").order("name").limit(limit ?? 100);
    if (!include_archived) q = q.eq("archived", false);
    if (search) q = q.or(`name.ilike.%${search}%,code.ilike.%${search}%,category.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/calculate-cost-draft.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";

// src/lib/costEngine.ts
var money = (value) => Math.round((value + Number.EPSILON) * 100) / 100;
function calculateCostSection(input) {
  const warnings = [];
  if (!(input.finishedSqm > 0)) throw new Error("finishedSqm must be greater than zero");
  if (input.riskPercent < 0) throw new Error("riskPercent cannot be negative");
  const referenceSqm = input.secondCutSqm && input.secondCutSqm > 0 ? input.secondCutSqm : input.finishedSqm;
  const allowedSlabSqm = money(input.finishedSqm * 1.3);
  if (input.slabSqm && input.slabSqm > allowedSlabSqm) {
    warnings.push(`Slab area ${input.slabSqm.toFixed(2)} sqm exceeds the +30% limit (${allowedSlabSqm.toFixed(2)} sqm).`);
  }
  const componentSubtotal = money(input.components.reduce((sum, component) => {
    if (component.quantity < 0 || component.unitPrice < 0) {
      throw new Error(`Negative value in component ${component.code}`);
    }
    return sum + component.quantity * component.unitPrice;
  }, 0));
  const riskBase = money(componentSubtotal + input.engobbio + input.finishCost);
  const riskAmount = money(riskBase * input.riskPercent / 100);
  const total = money(riskBase + riskAmount);
  const costPerSqm = money(total / referenceSqm);
  const tolerancePercent = input.averageTolerancePercent ?? 15;
  let status = "unavailable";
  let differencePercent = null;
  if (input.averageCostPerSqm && input.averageCostPerSqm > 0) {
    differencePercent = money((costPerSqm - input.averageCostPerSqm) / input.averageCostPerSqm * 100);
    status = differencePercent > tolerancePercent ? "above" : differencePercent < -tolerancePercent ? "below" : "within";
  }
  if (/deep/i.test(input.finish ?? "") && input.engobbio <= 0) {
    warnings.push("DEEP finish without an engobbio cost.");
  }
  return {
    name: input.name,
    referenceSqm: money(referenceSqm),
    allowedSlabSqm,
    componentSubtotal,
    engobbio: money(input.engobbio),
    finishCost: money(input.finishCost),
    riskBase,
    riskAmount,
    total,
    costPerSqm,
    averageCheck: { status, differencePercent, tolerancePercent },
    warnings
  };
}

// src/lib/mcp/tools/calculate-cost-draft.ts
var calculate_cost_draft_default = defineTool5({
  name: "calculate_cost_draft",
  title: "Calcola bozza costo",
  description: "Calcola in modo deterministico il costo di una sezione. Non salva e non modifica alcun preventivo.",
  inputSchema: {
    name: z5.string().min(1),
    finished_sqm: z5.number().positive(),
    second_cut_sqm: z5.number().positive().nullable().optional(),
    slab_sqm: z5.number().positive().nullable().optional(),
    finish: z5.string().nullable().optional(),
    components: z5.array(z5.object({
      code: z5.string().min(1),
      description: z5.string(),
      quantity: z5.number().nonnegative(),
      unit_price: z5.number().nonnegative()
    })),
    engobbio: z5.number().nonnegative(),
    finish_cost: z5.number().nonnegative(),
    risk_percent: z5.number().nonnegative(),
    average_cost_per_sqm: z5.number().positive().nullable().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args) => {
    const result = calculateCostSection({
      name: args.name,
      finishedSqm: args.finished_sqm,
      secondCutSqm: args.second_cut_sqm,
      slabSqm: args.slab_sqm,
      finish: args.finish,
      components: args.components.map((item) => ({
        code: item.code,
        description: item.description,
        quantity: item.quantity,
        unitPrice: item.unit_price
      })),
      engobbio: args.engobbio,
      finishCost: args.finish_cost,
      riskPercent: args.risk_percent,
      averageCostPerSqm: args.average_cost_per_sqm,
      averageTolerancePercent: 15
    });
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { result }
    };
  }
});

// src/lib/mcp/tools/import-zoho-project-draft.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
var import_zoho_project_draft_default = defineTool6({
  name: "import_zoho_project_draft",
  title: "Importa progetto Zoho in bozza",
  description: "Legge Deal, quotation, note e allegati da Zoho e genera un dossier tecnico. Non modifica Zoho o WorkDrive.",
  inputSchema: { deal_id: z6.string().regex(/^\d{10,25}$/).describe("ID numerico del Deal Zoho") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ deal_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    const response = await fetch(`${process.env.SUPABASE_URL}/functions/v1/zoho-project-draft`, { method: "POST", headers: { Authorization: `Bearer ${ctx.getToken()}`, "Content-Type": "application/json" }, body: JSON.stringify({ deal_id, write_to_workdrive: false }) });
    const payload = await response.json();
    if (!response.ok) return { content: [{ type: "text", text: payload.error ?? "Import failed" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ahyazehjcodmvyddchuk";
var mcp_default = defineMcp({
  name: "preventivi-ranieri-mcp",
  title: "Preventivi Ranieri",
  version: "0.3.0",
  instructions: "Strumenti in sola lettura per consultare preventivi, clienti e prodotti, importare dossier Zoho e calcolare bozze costo deterministiche. Nessuna modifica automatica dei record CRM.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_quotes_default, get_quote_default, list_clients_default, list_products_default, calculate_cost_draft_default, import_zoho_project_draft_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
